import {
  User,
  UserRole,
  Floor,
  Room,
  RoomType,
  RoomStatus,
  RoomAllocation,
  RentHistory,
  RentStatus,
  Transaction,
  TransactionType,
  PaymentMethod,
  MealTiming,
  MealType,
  DailyMenu,
  DayOfWeek,
  MealToken,
  Complaint,
  ComplaintStatus,
  DiscussionPost,
  PaymentRequest,
  PaymentRequestStatus,
  Meal,
  DashboardStats,
} from "./types";

// Current logged in user (for demo purposes)
export const currentUser: User = {
  id: "user-001",
  name: "Rahim Ahmed",
  email: "rahim.ahmed@example.com",
  phone: "+880 1712-345678",
  role: UserRole.TENANT,
  isVerified: true,
  isActive: true,
  avatarUrl: "/placeholder-user.jpg",
  createdAt: "2024-01-15T10:00:00Z",
  roomId: "room-101",
  walletBalance: 5000,
};

// Mock Users
export const mockUsers: User[] = [
  currentUser,
  {
    id: "user-002",
    name: "Karim Hassan",
    email: "karim.hassan@example.com",
    phone: "+880 1812-456789",
    role: UserRole.TENANT,
    isVerified: true,
    isActive: true,
    avatarUrl: "/placeholder-user.jpg",
    createdAt: "2024-02-10T09:30:00Z",
    roomId: "room-102",
    walletBalance: 3500,
  },
  {
    id: "user-003",
    name: "Fatima Begum",
    email: "fatima.begum@example.com",
    phone: "+880 1912-567890",
    role: UserRole.TENANT,
    isVerified: false,
    isActive: true,
    createdAt: "2024-03-05T14:20:00Z",
    walletBalance: 0,
  },
  {
    id: "user-004",
    name: "Abdul Jabbar",
    email: "abdul.jabbar@example.com",
    phone: "+880 1612-678901",
    role: UserRole.TENANT,
    isVerified: true,
    isActive: true,
    avatarUrl: "/placeholder-user.jpg",
    createdAt: "2024-01-20T11:45:00Z",
    roomId: "room-201",
    walletBalance: 6000,
  },
  {
    id: "user-005",
    name: "Nusrat Jahan",
    email: "nusrat.jahan@example.com",
    phone: "+880 1512-789012",
    role: UserRole.TENANT,
    isVerified: true,
    isActive: true,
    createdAt: "2024-02-28T16:00:00Z",
    roomId: "room-202",
    walletBalance: 2000,
  },
  {
    id: "admin-001",
    name: "Mohammad Ali",
    email: "admin@hostel.com",
    phone: "+880 1712-111222",
    role: UserRole.ADMIN,
    isVerified: true,
    isActive: true,
    avatarUrl: "/placeholder-user.jpg",
    createdAt: "2023-06-01T08:00:00Z",
    walletBalance: 0,
  },
  {
    id: "admin-002",
    name: "Ayesha Khan",
    email: "ayesha.admin@hostel.com",
    phone: "+880 1812-222333",
    role: UserRole.ADMIN,
    isVerified: true,
    isActive: true,
    createdAt: "2023-08-15T09:00:00Z",
    walletBalance: 0,
  },
];

// Mock Floors
export const mockFloors: Floor[] = [
  { id: "floor-1", name: "Ground Floor", floorNumber: 0, description: "Reception and common areas" },
  { id: "floor-2", name: "First Floor", floorNumber: 1, description: "Single and double rooms" },
  { id: "floor-3", name: "Second Floor", floorNumber: 2, description: "Double and triple rooms" },
  { id: "floor-4", name: "Third Floor", floorNumber: 3, description: "Dormitory rooms" },
];

// Mock Rooms
export const mockRooms: Room[] = [
  {
    id: "room-101",
    roomNumber: "101",
    floorId: "floor-2",
    floorName: "First Floor",
    floor: 1,
    roomType: RoomType.SINGLE,
    type: RoomType.SINGLE,
    capacity: 1,
    occupancy: 1,
    currentOccupancy: 1,
    rentAmount: 8000,
    status: RoomStatus.OCCUPIED,
    amenities: ["WiFi", "AC", "Attached Bathroom"],
  },
  {
    id: "room-102",
    roomNumber: "102",
    floorId: "floor-2",
    floorName: "First Floor",
    floor: 1,
    roomType: RoomType.SINGLE,
    type: RoomType.SINGLE,
    capacity: 1,
    occupancy: 1,
    currentOccupancy: 1,
    rentAmount: 8000,
    status: RoomStatus.OCCUPIED,
    amenities: ["WiFi", "AC", "Attached Bathroom"],
  },
  {
    id: "room-103",
    roomNumber: "103",
    floorId: "floor-2",
    floorName: "First Floor",
    floor: 1,
    roomType: RoomType.DOUBLE,
    type: RoomType.DOUBLE,
    capacity: 2,
    occupancy: 0,
    currentOccupancy: 0,
    rentAmount: 6000,
    status: RoomStatus.AVAILABLE,
    amenities: ["WiFi", "Fan", "Shared Bathroom"],
  },
  {
    id: "room-201",
    roomNumber: "201",
    floorId: "floor-3",
    floorName: "Second Floor",
    floor: 2,
    roomType: RoomType.DOUBLE,
    type: RoomType.DOUBLE,
    capacity: 2,
    occupancy: 1,
    currentOccupancy: 1,
    rentAmount: 6000,
    status: RoomStatus.OCCUPIED,
    amenities: ["WiFi", "Fan", "Attached Bathroom"],
  },
  {
    id: "room-202",
    roomNumber: "202",
    floorId: "floor-3",
    floorName: "Second Floor",
    floor: 2,
    roomType: RoomType.TRIPLE,
    type: RoomType.TRIPLE,
    capacity: 3,
    occupancy: 1,
    currentOccupancy: 1,
    rentAmount: 5000,
    status: RoomStatus.OCCUPIED,
    amenities: ["WiFi", "Fan", "Shared Bathroom"],
  },
  {
    id: "room-301",
    roomNumber: "301",
    floorId: "floor-4",
    floorName: "Third Floor",
    floor: 3,
    roomType: RoomType.DORMITORY,
    type: RoomType.DORMITORY,
    capacity: 6,
    occupancy: 4,
    currentOccupancy: 4,
    rentAmount: 3500,
    status: RoomStatus.OCCUPIED,
    amenities: ["WiFi", "Fan", "Shared Bathroom", "Locker"],
  },
  {
    id: "room-302",
    roomNumber: "302",
    floorId: "floor-4",
    floorName: "Third Floor",
    floor: 3,
    roomType: RoomType.DORMITORY,
    type: RoomType.DORMITORY,
    capacity: 6,
    occupancy: 0,
    currentOccupancy: 0,
    rentAmount: 3500,
    status: RoomStatus.MAINTENANCE,
    amenities: ["WiFi", "Fan", "Shared Bathroom", "Locker"],
  },
];

// Mock Room Allocations
export const mockRoomAllocations: RoomAllocation[] = [
  {
    id: "alloc-001",
    roomId: "room-101",
    userId: "user-001",
    userName: "Rahim Ahmed",
    roomNumber: "101",
    allocatedAt: "2024-01-15T10:00:00Z",
    startDate: "2024-01-15T10:00:00Z",
    isActive: true,
  },
  {
    id: "alloc-002",
    roomId: "room-102",
    userId: "user-002",
    userName: "Karim Hassan",
    roomNumber: "102",
    allocatedAt: "2024-02-10T09:30:00Z",
    startDate: "2024-02-10T09:30:00Z",
    isActive: true,
  },
  {
    id: "alloc-003",
    roomId: "room-201",
    userId: "user-004",
    userName: "Abdul Jabbar",
    roomNumber: "201",
    allocatedAt: "2024-01-20T11:45:00Z",
    startDate: "2024-01-20T11:45:00Z",
    isActive: true,
  },
  {
    id: "alloc-004",
    roomId: "room-202",
    userId: "user-005",
    userName: "Nusrat Jahan",
    roomNumber: "202",
    allocatedAt: "2024-02-28T16:00:00Z",
    startDate: "2024-02-28T16:00:00Z",
    isActive: true,
  },
];

// Mock Rent History
export const mockRentHistory: RentHistory[] = [
  {
    id: "rent-001",
    userId: "user-001",
    roomId: "room-101",
    amount: 8000,
    month: "January 2024",
    year: 2024,
    isPaid: true,
    paidAt: "2024-01-05T10:00:00Z",
    paidDate: "2024-01-05T10:00:00Z",
    dueDate: "2024-01-05T00:00:00Z",
    status: RentStatus.PAID,
    paymentMethod: PaymentMethod.BKASH,
  },
  {
    id: "rent-002",
    userId: "user-001",
    roomId: "room-101",
    amount: 8000,
    month: "February 2024",
    year: 2024,
    isPaid: true,
    paidAt: "2024-02-03T14:30:00Z",
    paidDate: "2024-02-03T14:30:00Z",
    dueDate: "2024-02-05T00:00:00Z",
    status: RentStatus.PAID,
    paymentMethod: PaymentMethod.NAGAD,
  },
  {
    id: "rent-003",
    userId: "user-001",
    roomId: "room-101",
    amount: 8000,
    month: "March 2024",
    year: 2024,
    isPaid: true,
    paidAt: "2024-03-07T09:15:00Z",
    paidDate: "2024-03-07T09:15:00Z",
    dueDate: "2024-03-05T00:00:00Z",
    status: RentStatus.PAID,
    paymentMethod: PaymentMethod.ONLINE,
  },
  {
    id: "rent-004",
    userId: "user-001",
    roomId: "room-101",
    amount: 8000,
    month: "April 2024",
    year: 2024,
    isPaid: false,
    dueDate: "2024-04-05T00:00:00Z",
    status: RentStatus.PENDING,
  },
  {
    id: "rent-005",
    userId: "user-002",
    roomId: "room-102",
    amount: 8000,
    month: "April 2024",
    year: 2024,
    isPaid: false,
    dueDate: "2024-04-05T00:00:00Z",
    status: RentStatus.OVERDUE,
  },
];

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: "txn-001",
    userId: "user-001",
    userName: "Rahim Ahmed",
    type: TransactionType.CREDIT,
    amount: 8000,
    description: "Room Rent - January 2024",
    paymentMethod: PaymentMethod.BKASH,
    createdAt: "2024-01-05T10:00:00Z",
    reference: "BKS123456789",
  },
  {
    id: "txn-002",
    userId: "user-001",
    userName: "Rahim Ahmed",
    type: TransactionType.CREDIT,
    amount: 8000,
    description: "Room Rent - February 2024",
    paymentMethod: PaymentMethod.NAGAD,
    createdAt: "2024-02-03T14:30:00Z",
    reference: "NGD987654321",
  },
  {
    id: "txn-003",
    userId: "user-002",
    userName: "Karim Hassan",
    type: TransactionType.CREDIT,
    amount: 8000,
    description: "Room Rent - February 2024",
    paymentMethod: PaymentMethod.ROCKET,
    createdAt: "2024-02-05T11:20:00Z",
    reference: "RKT456789123",
  },
  {
    id: "txn-004",
    userId: "user-001",
    userName: "Rahim Ahmed",
    type: TransactionType.CREDIT,
    amount: 500,
    description: "Meal Tokens - 10 Breakfast",
    paymentMethod: PaymentMethod.BKASH,
    createdAt: "2024-03-01T08:00:00Z",
    reference: "BKS111222333",
  },
  {
    id: "txn-005",
    userId: "user-004",
    userName: "Abdul Jabbar",
    type: TransactionType.CREDIT,
    amount: 6000,
    description: "Room Rent - March 2024",
    paymentMethod: PaymentMethod.ONLINE,
    createdAt: "2024-03-02T15:45:00Z",
    reference: "ONL789456123",
  },
  {
    id: "txn-006",
    userId: "admin-001",
    userName: "Mohammad Ali",
    type: TransactionType.DEBIT,
    amount: 15000,
    description: "Utility Bill Payment - March 2024",
    paymentMethod: PaymentMethod.ONLINE,
    createdAt: "2024-03-10T10:00:00Z",
    reference: "UTL456123789",
  },
];

// Mock Meal Timings
export const mockMealTimings: MealTiming[] = [
  { id: "timing-1", mealType: MealType.BREAKFAST, startTime: "07:00", endTime: "09:00" },
  { id: "timing-2", mealType: MealType.LUNCH, startTime: "12:30", endTime: "14:30" },
  { id: "timing-3", mealType: MealType.DINNER, startTime: "19:00", endTime: "21:00" },
];

// Helper function to create a meal
const createMeal = (type: MealType, mainCourse: string, sideDish?: string, dessert?: string): Meal => ({
  type,
  mainCourse,
  sideDish,
  dessert,
});

// Mock Daily Menus with correct structure for pages
export const mockDailyMenus: (DailyMenu & { meals: Meal[] })[] = [
  {
    id: "menu-sun",
    dayOfWeek: DayOfWeek.SUNDAY,
    mealType: MealType.BREAKFAST,
    items: [
      { id: "item-1", name: "Paratha", description: "Layered flatbread" },
      { id: "item-2", name: "Egg Curry", description: "Spiced egg curry" },
      { id: "item-3", name: "Tea", description: "Hot milk tea" },
    ],
    meals: [
      createMeal(MealType.BREAKFAST, "Paratha with Egg Curry", "Chutney"),
      createMeal(MealType.LUNCH, "Rice with Chicken Curry", "Dal & Salad"),
      createMeal(MealType.DINNER, "Rice with Fish Curry", "Mixed Vegetables"),
    ],
    isActive: true,
  },
  {
    id: "menu-mon",
    dayOfWeek: DayOfWeek.MONDAY,
    mealType: MealType.BREAKFAST,
    items: [
      { id: "item-11", name: "Toast & Butter", description: "Toasted bread with butter" },
      { id: "item-12", name: "Omelette", description: "Vegetable omelette" },
      { id: "item-13", name: "Banana", description: "Fresh banana" },
    ],
    meals: [
      createMeal(MealType.BREAKFAST, "Toast with Omelette", "Fresh Fruit"),
      createMeal(MealType.LUNCH, "Rice with Beef Bhuna", "Red Lentil Soup"),
      createMeal(MealType.DINNER, "Khichuri", "Egg Bhaji", "Pickle"),
    ],
    isActive: true,
  },
  {
    id: "menu-tue",
    dayOfWeek: DayOfWeek.TUESDAY,
    mealType: MealType.BREAKFAST,
    items: [
      { id: "item-20", name: "Puri", description: "Deep-fried bread" },
      { id: "item-21", name: "Halwa", description: "Semolina pudding" },
      { id: "item-22", name: "Tea", description: "Hot milk tea" },
    ],
    meals: [
      createMeal(MealType.BREAKFAST, "Puri with Halwa", "Tea"),
      createMeal(MealType.LUNCH, "Chicken Biryani", "Raita", "Salad"),
      createMeal(MealType.DINNER, "Chapati with Paneer", "Dal Fry"),
    ],
    isActive: true,
  },
  {
    id: "menu-wed",
    dayOfWeek: DayOfWeek.WEDNESDAY,
    mealType: MealType.BREAKFAST,
    items: [
      { id: "item-30", name: "Idli", description: "Steamed rice cakes" },
      { id: "item-31", name: "Sambar", description: "Lentil vegetable stew" },
    ],
    meals: [
      createMeal(MealType.BREAKFAST, "Idli Sambar", "Coconut Chutney"),
      createMeal(MealType.LUNCH, "Rice with Mutton Curry", "Vegetable Side"),
      createMeal(MealType.DINNER, "Fried Rice", "Manchurian"),
    ],
    isActive: true,
  },
  {
    id: "menu-thu",
    dayOfWeek: DayOfWeek.THURSDAY,
    mealType: MealType.BREAKFAST,
    items: [
      { id: "item-40", name: "Dosa", description: "Crispy rice crepe" },
      { id: "item-41", name: "Chutney", description: "Coconut chutney" },
    ],
    meals: [
      createMeal(MealType.BREAKFAST, "Masala Dosa", "Sambar & Chutney"),
      createMeal(MealType.LUNCH, "Rice with Fish Fry", "Dal & Salad"),
      createMeal(MealType.DINNER, "Roti with Chicken", "Mixed Vegetables"),
    ],
    isActive: true,
  },
  {
    id: "menu-fri",
    dayOfWeek: DayOfWeek.FRIDAY,
    mealType: MealType.BREAKFAST,
    items: [
      { id: "item-50", name: "Luchi", description: "Deep fried flatbread" },
      { id: "item-51", name: "Chole", description: "Chickpea curry" },
    ],
    meals: [
      createMeal(MealType.BREAKFAST, "Luchi with Chole", "Pickle"),
      createMeal(MealType.LUNCH, "Special Biryani", "Raita", "Sweet"),
      createMeal(MealType.DINNER, "Pulao with Korma", "Salad"),
    ],
    isActive: true,
  },
  {
    id: "menu-sat",
    dayOfWeek: DayOfWeek.SATURDAY,
    mealType: MealType.BREAKFAST,
    items: [
      { id: "item-60", name: "Pancakes", description: "Fluffy pancakes" },
      { id: "item-61", name: "Honey", description: "Natural honey" },
    ],
    meals: [
      createMeal(MealType.BREAKFAST, "Pancakes with Honey", "Fresh Juice"),
      createMeal(MealType.LUNCH, "Rice with Prawn Curry", "Vegetables"),
      createMeal(MealType.DINNER, "Naan with Butter Chicken", "Dal Makhani", "Gulab Jamun"),
    ],
    isActive: true,
  },
];

// Mock Meal Tokens
export const mockMealTokens: MealToken[] = [
  {
    id: "token-001",
    userId: "user-001",
    mealType: MealType.BREAKFAST,
    date: "2024-03-15",
    isUsed: true,
    purchasedAt: "2024-03-01T08:00:00Z",
    usedAt: "2024-03-15T07:30:00Z",
    price: 50,
  },
  {
    id: "token-002",
    userId: "user-001",
    mealType: MealType.LUNCH,
    date: "2024-03-15",
    isUsed: true,
    purchasedAt: "2024-03-01T08:00:00Z",
    usedAt: "2024-03-15T12:45:00Z",
    price: 80,
  },
  {
    id: "token-003",
    userId: "user-001",
    mealType: MealType.DINNER,
    date: "2024-03-15",
    isUsed: false,
    purchasedAt: "2024-03-01T08:00:00Z",
    price: 80,
  },
  {
    id: "token-004",
    userId: "user-001",
    mealType: MealType.BREAKFAST,
    date: "2024-03-16",
    isUsed: false,
    purchasedAt: "2024-03-01T08:00:00Z",
    price: 50,
  },
  {
    id: "token-005",
    userId: "user-001",
    mealType: MealType.LUNCH,
    date: "2024-03-16",
    isUsed: false,
    purchasedAt: "2024-03-01T08:00:00Z",
    price: 80,
  },
  {
    id: "token-006",
    userId: "user-002",
    mealType: MealType.BREAKFAST,
    date: "2024-03-15",
    isUsed: true,
    purchasedAt: "2024-03-01T09:00:00Z",
    usedAt: "2024-03-15T08:00:00Z",
    price: 50,
  },
  {
    id: "token-007",
    userId: "user-002",
    mealType: MealType.LUNCH,
    date: "2024-03-15",
    isUsed: false,
    purchasedAt: "2024-03-01T09:00:00Z",
    price: 80,
  },
];

// Mock Complaints
export const mockComplaints: Complaint[] = [
  {
    id: "complaint-001",
    userId: "user-001",
    userName: "Rahim Ahmed",
    title: "AC Not Working",
    description: "The air conditioner in Room 101 has stopped working since yesterday. It makes a strange noise but doesn't cool the room.",
    category: "Maintenance",
    status: ComplaintStatus.IN_PROGRESS,
    createdAt: "2024-03-10T14:30:00Z",
    updatedAt: "2024-03-11T09:00:00Z",
    adminResponse: "We have scheduled a technician visit for tomorrow.",
  },
  {
    id: "complaint-002",
    userId: "user-002",
    userName: "Karim Hassan",
    title: "WiFi Connectivity Issues",
    description: "The WiFi signal is very weak in Room 102. I cannot attend my online classes properly.",
    category: "Facilities",
    status: ComplaintStatus.PENDING,
    createdAt: "2024-03-12T10:15:00Z",
    updatedAt: "2024-03-12T10:15:00Z",
  },
  {
    id: "complaint-003",
    userId: "user-004",
    userName: "Abdul Jabbar",
    title: "Water Leakage in Bathroom",
    description: "There is a water leakage from the ceiling of the bathroom in Room 201. It gets worse when someone uses the bathroom above.",
    category: "Maintenance",
    status: ComplaintStatus.RESOLVED,
    createdAt: "2024-03-05T08:45:00Z",
    updatedAt: "2024-03-08T16:30:00Z",
    adminResponse: "The plumbing issue has been fixed. Please let us know if the problem persists.",
  },
  {
    id: "complaint-004",
    userId: "user-005",
    userName: "Nusrat Jahan",
    title: "Noisy Neighbors",
    description: "The residents in the adjacent room play loud music late at night, disturbing my sleep.",
    category: "Noise",
    status: ComplaintStatus.REJECTED,
    createdAt: "2024-03-01T22:00:00Z",
    updatedAt: "2024-03-03T10:00:00Z",
    adminResponse: "We have spoken to the residents and they have agreed to keep the volume down after 10 PM.",
  },
  {
    id: "complaint-005",
    userId: "user-001",
    userName: "Rahim Ahmed",
    title: "Food Quality Issue",
    description: "The lunch served yesterday was not fresh. Several residents felt sick after eating.",
    category: "Food Quality",
    status: ComplaintStatus.PENDING,
    createdAt: "2024-03-14T16:00:00Z",
    updatedAt: "2024-03-14T16:00:00Z",
  },
];

// Mock Discussion Posts
export const mockDiscussionPosts: DiscussionPost[] = [
  {
    id: "post-001",
    userId: "user-001",
    authorId: "user-001",
    userName: "Rahim Ahmed",
    userAvatar: "/placeholder-user.jpg",
    content: "Is anyone interested in forming a study group for the upcoming exams? We could use the common room on the ground floor.",
    createdAt: "2024-03-14T18:30:00Z",
    likes: 5,
    isPinned: false,
    replies: [
      {
        id: "reply-001",
        userId: "user-002",
        userName: "Karim Hassan",
        userAvatar: "/placeholder-user.jpg",
        content: "I'm interested! What subjects are you focusing on?",
        createdAt: "2024-03-14T19:00:00Z",
      },
      {
        id: "reply-002",
        userId: "user-004",
        userName: "Abdul Jabbar",
        content: "Count me in too. How about we meet this Saturday at 4 PM?",
        createdAt: "2024-03-14T19:30:00Z",
      },
    ],
    comments: [
      {
        id: "reply-001",
        userId: "user-002",
        userName: "Karim Hassan",
        userAvatar: "/placeholder-user.jpg",
        content: "I'm interested! What subjects are you focusing on?",
        createdAt: "2024-03-14T19:00:00Z",
      },
      {
        id: "reply-002",
        userId: "user-004",
        userName: "Abdul Jabbar",
        content: "Count me in too. How about we meet this Saturday at 4 PM?",
        createdAt: "2024-03-14T19:30:00Z",
      },
    ],
  },
  {
    id: "post-002",
    userId: "user-005",
    authorId: "user-005",
    userName: "Nusrat Jahan",
    content: "The new meal menu for this week looks great! Really appreciate the variety. Thank you to the kitchen staff!",
    createdAt: "2024-03-13T12:15:00Z",
    likes: 12,
    isPinned: true,
    replies: [
      {
        id: "reply-003",
        userId: "user-001",
        userName: "Rahim Ahmed",
        userAvatar: "/placeholder-user.jpg",
        content: "Agreed! The biryani on Tuesday was amazing!",
        createdAt: "2024-03-13T13:00:00Z",
      },
    ],
    comments: [
      {
        id: "reply-003",
        userId: "user-001",
        userName: "Rahim Ahmed",
        userAvatar: "/placeholder-user.jpg",
        content: "Agreed! The biryani on Tuesday was amazing!",
        createdAt: "2024-03-13T13:00:00Z",
      },
    ],
  },
  {
    id: "post-003",
    userId: "user-002",
    authorId: "user-002",
    userName: "Karim Hassan",
    userAvatar: "/placeholder-user.jpg",
    content: "Has anyone seen my blue umbrella? I think I left it in the common room yesterday evening.",
    createdAt: "2024-03-12T09:45:00Z",
    likes: 2,
    isPinned: false,
    replies: [],
    comments: [],
  },
];

// Mock Payment Requests
export const mockPaymentRequests: PaymentRequest[] = [
  {
    id: "req-001",
    userId: "user-001",
    requesterId: "user-001",
    userName: "Rahim Ahmed",
    amount: 8000,
    description: "Room Rent - April 2024",
    dueDate: "2024-04-05",
    isPaid: false,
    status: PaymentRequestStatus.PENDING,
    paymentMethod: PaymentMethod.BKASH,
    transactionReference: "BKS789456123",
    createdAt: "2024-03-25T10:00:00Z",
  },
  {
    id: "req-002",
    userId: "user-002",
    requesterId: "user-002",
    userName: "Karim Hassan",
    amount: 8000,
    description: "Room Rent - April 2024",
    dueDate: "2024-04-05",
    isPaid: false,
    status: PaymentRequestStatus.APPROVED,
    paymentMethod: PaymentMethod.UPI,
    transactionReference: "UPI456789123",
    adminNotes: "Payment verified",
    createdAt: "2024-03-25T10:00:00Z",
  },
  {
    id: "req-003",
    userId: "user-004",
    requesterId: "user-004",
    userName: "Abdul Jabbar",
    amount: 6000,
    description: "Room Rent - April 2024",
    dueDate: "2024-04-05",
    isPaid: false,
    status: PaymentRequestStatus.REJECTED,
    paymentMethod: PaymentMethod.BANK_TRANSFER,
    transactionReference: "BANK123456",
    adminNotes: "Transaction reference not found",
    createdAt: "2024-03-25T10:00:00Z",
  },
  {
    id: "req-004",
    userId: "user-005",
    requesterId: "user-005",
    userName: "Nusrat Jahan",
    amount: 5000,
    description: "Room Rent - April 2024",
    dueDate: "2024-04-05",
    isPaid: false,
    status: PaymentRequestStatus.PENDING,
    paymentMethod: PaymentMethod.CASH,
    createdAt: "2024-03-26T14:00:00Z",
  },
];

// Dashboard Statistics (for Admin)
export const adminDashboardStats = {
  totalUsers: mockUsers.filter((u) => u.role === UserRole.TENANT).length,
  verifiedUsers: mockUsers.filter((u) => u.role === UserRole.TENANT && u.isVerified).length,
  totalRooms: mockRooms.length,
  occupiedRooms: mockRooms.filter((r) => r.status === RoomStatus.OCCUPIED).length,
  availableRooms: mockRooms.filter((r) => r.status === RoomStatus.AVAILABLE).length,
  pendingComplaints: mockComplaints.filter((c) => c.status === ComplaintStatus.PENDING).length,
  totalRevenue: mockTransactions
    .filter((t) => t.type === TransactionType.CREDIT)
    .reduce((sum, t) => sum + t.amount, 0),
  totalExpenses: mockTransactions
    .filter((t) => t.type === TransactionType.DEBIT)
    .reduce((sum, t) => sum + t.amount, 0),
};

// Mock Dashboard Stats for Financials
export const mockDashboardStats: DashboardStats = {
  totalRevenue: mockTransactions
    .filter((t) => t.type === TransactionType.CREDIT)
    .reduce((sum, t) => sum + t.amount, 0),
  pendingRent: mockRentHistory
    .filter((r) => r.status === RentStatus.PENDING)
    .reduce((sum, r) => sum + r.amount, 0),
  overdueAmount: mockRentHistory
    .filter((r) => r.status === RentStatus.OVERDUE)
    .reduce((sum, r) => sum + r.amount, 0),
  totalUsers: mockUsers.filter((u) => u.role === UserRole.TENANT).length,
  verifiedUsers: mockUsers.filter((u) => u.role === UserRole.TENANT && u.isVerified).length,
  totalRooms: mockRooms.length,
  occupiedRooms: mockRooms.filter((r) => r.status === RoomStatus.OCCUPIED).length,
  availableRooms: mockRooms.filter((r) => r.status === RoomStatus.AVAILABLE).length,
  pendingComplaints: mockComplaints.filter((c) => c.status === ComplaintStatus.PENDING).length,
  totalExpenses: mockTransactions
    .filter((t) => t.type === TransactionType.DEBIT)
    .reduce((sum, t) => sum + t.amount, 0),
};

// Helper function to get current day's menu
export function getTodayMenu(): (DailyMenu & { meals: Meal[] })[] {
  const days = ["SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY"];
  const today = days[new Date().getDay()] as DayOfWeek;
  return mockDailyMenus.filter((menu) => menu.dayOfWeek === today);
}

// Helper function to get user's room
export function getUserRoom(userId: string): Room | undefined {
  const user = mockUsers.find((u) => u.id === userId);
  if (!user?.roomId) return undefined;
  return mockRooms.find((r) => r.id === user.roomId);
}

// Helper function to get rent due
export function getRentDue(userId: string): RentHistory | undefined {
  return mockRentHistory.find((r) => r.userId === userId && !r.isPaid);
}
